spring:
  application:
    name: agriconnect-annuaire
server:
  port: 8761

eureka:
  instance:
    hostname: annuaire
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#        Avec Docker
#        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#        Sans Docker
      defaultZone: http://localhost:${server.port}/eureka/

